### ISSUE TITLE
0.3.0 Release Plan

### ISSUE THREAD

**Issue by RussBaz** [RussBaz/enforce#25]
- [x] Add support for **Generics**
- [x] Refactor settings and add new options (#4, #10, #14, #20)
  - **BREAKING CHANGE:** updated config syntax - dictionary with configuration options is now passed to a `config` function. Reset to default functionality was also added.
  - Default type checking mode is set to invariant - but perhaps should be covariant? (`issubclass` is covariant)
  - Also covariant, contravariant and bivariant modes are available
- [x] Add support for `__subclasscheck__`, `__subclasshook__` and **ABCs** (#21, #23)
- [x] `__no_type_check__` is now respected (#26)
- [x] Fixed tests which were not cleaning up after themselves after changing the global settings (#24)
- [X] Add updated README
- [X] ~~Update Wiki page for settings~~
- [x] Upload 0.3.0 to PyPI

**Comment by RussBaz** [comment]
@willzfarmer I just pushed this version to PyPI! Congratulations!
